### ISSUE TITLE
Update for OMV 4

### ISSUE THREAD

**Issue by Supersimo88** [Obihoernchen/openmediavault-monitoring-odroid-xu4#4]
It would be great if you could update the plugins to make them compatible with OMV4

**Comment by akidburn** [comment]
@Supersimo88 
updated at 
https://github.com/akidburn/openmediavault-monitoring-odroid-xu4

**Comment by yunweiyuan** [comment]
@akidburn Thank you so much for your effort! But it seems the plugin still doesn't work on my side.

**Comment by akidburn** [comment]
@Supersimo88 @yunweiyuan 
updated fanspeed for omv 4

**Comment by yunweiyuan** [comment]
@akidburn Humm weird. I found none of my plugins works since installed old version plugins. Are these services stopped by accident?

**Comment by Obihoernchen** [comment]
Merged #5
